# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qcrocoflow_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qcrocoflowDockWidgetBase(object):
    def setupUi(self, qcrocoflowDockWidgetBase):
        qcrocoflowDockWidgetBase.setObjectName("qcrocoflowDockWidgetBase")
        qcrocoflowDockWidgetBase.resize(697, 141)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        qcrocoflowDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(qcrocoflowDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(qcrocoflowDockWidgetBase)

    def retranslateUi(self, qcrocoflowDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        qcrocoflowDockWidgetBase.setWindowTitle(_translate("qcrocoflowDockWidgetBase", "QCrocoFlow"))
