# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qcrocoflow_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qcrocoflowDialogBase(object):
    def setupUi(self, qcrocoflowDialogBase):
        qcrocoflowDialogBase.setObjectName("qcrocoflowDialogBase")
        qcrocoflowDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(qcrocoflowDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(qcrocoflowDialogBase)
        self.button_box.accepted.connect(qcrocoflowDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(qcrocoflowDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(qcrocoflowDialogBase)

    def retranslateUi(self, qcrocoflowDialogBase):
        _translate = QtCore.QCoreApplication.translate
        qcrocoflowDialogBase.setWindowTitle(_translate("qcrocoflowDialogBase", "qc"))
