# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qcrocoflow_timereference_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_timeReferenceDialog(object):
    def setupUi(self, timeReferenceDialog):
        timeReferenceDialog.setObjectName("timeReferenceDialog")
        timeReferenceDialog.resize(356, 211)
        self.buttonBox = QtWidgets.QDialogButtonBox(timeReferenceDialog)
        self.buttonBox.setGeometry(QtCore.QRect(0, 170, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(timeReferenceDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 208, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(timeReferenceDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 145, 17))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(timeReferenceDialog)
        self.widget.setGeometry(QtCore.QRect(10, 50, 331, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.crocoTimeReferenceRadioButton = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.crocoTimeReferenceRadioButton.setFont(font)
        self.crocoTimeReferenceRadioButton.setObjectName("crocoTimeReferenceRadioButton")
        self.horizontalLayout.addWidget(self.crocoTimeReferenceRadioButton)
        self.pythonTimeReferenceRadioButton = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pythonTimeReferenceRadioButton.setFont(font)
        self.pythonTimeReferenceRadioButton.setChecked(True)
        self.pythonTimeReferenceRadioButton.setObjectName("pythonTimeReferenceRadioButton")
        self.horizontalLayout.addWidget(self.pythonTimeReferenceRadioButton)
        self.widget1 = QtWidgets.QWidget(timeReferenceDialog)
        self.widget1.setGeometry(QtCore.QRect(10, 120, 331, 29))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minDateTimeWidget = QtWidgets.QDateTimeEdit(self.widget1)
        self.minDateTimeWidget.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.minDateTimeWidget.setFont(font)
        self.minDateTimeWidget.setObjectName("minDateTimeWidget")
        self.horizontalLayout_2.addWidget(self.minDateTimeWidget)
        self.maxDateTimeWidget = QtWidgets.QDateTimeEdit(self.widget1)
        self.maxDateTimeWidget.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxDateTimeWidget.setFont(font)
        self.maxDateTimeWidget.setObjectName("maxDateTimeWidget")
        self.horizontalLayout_2.addWidget(self.maxDateTimeWidget)

        self.retranslateUi(timeReferenceDialog)
        self.buttonBox.accepted.connect(timeReferenceDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(timeReferenceDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(timeReferenceDialog)

    def retranslateUi(self, timeReferenceDialog):
        _translate = QtCore.QCoreApplication.translate
        timeReferenceDialog.setWindowTitle(_translate("timeReferenceDialog", "Dialog"))
        self.label.setText(_translate("timeReferenceDialog", "Select time reference"))
        self.label_2.setText(_translate("timeReferenceDialog", "Current time range found"))
        self.crocoTimeReferenceRadioButton.setText(_translate("timeReferenceDialog", "1990-01-01"))
        self.pythonTimeReferenceRadioButton.setText(_translate("timeReferenceDialog", "1970-01-01"))
