# -*- coding: utf-8 -*-
"""
/***************************************************************************
 croco
                                 A QGIS plugin
 croco_grid
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-03
        copyright            : (C) 2023 by john nejmann
        email                : @
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load croco class from file croco.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qcrocoflow_crocogrid import qcrocoflow_crocogrid
    return qcrocoflow_crocogrid(iface)
